name: Ingest Tweets

# Run this workflow on pushes to the repository or on a schedule
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"  # Runs every hour

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Adjust version as needed

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Run the ingestion script
      - name: Fetch Tweets with ingest_tweets.py
        env:
          BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        run: |
          source venv/bin/activate
          python scripts/ingest_tweets.py

      # Send raw_tweets.json to Foundry
      - name: Send Tweets to Foundry
        env:
          TWEET_FOUNDRY_TOKEN: ${{ secrets.TWEET_FOUNDRY_TOKEN }}
        run: |
          source venv/bin/activate
          python scripts/send_tweets.py

      # Commit and push the output if raw_tweets.json was updated
      - name: Commit and push raw_tweets.json
        run: |
          if [ -s raw_tweets.json ]; then
            git config --global user.name "MHeidacker"
            git config --global user.email "max@heidacker.ai"
            git add raw_tweets.json
            git commit -m "Update raw_tweets.json"
            git push
          else
            echo "raw_tweets.json is empty or unchanged. Skipping commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
