name: Ingest Data

# Run this workflow on pushes to the repository or on a schedule
on:
  push:
      branches:
        - main
  schedule:
    - cron: "0 7 * * *"  # Runs every day

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Adjust version as needed

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Run the Twitter ingestion script
      - name: Fetch Tweets with ingest_tweets.py
        env:
          BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        run: |
          source venv/bin/activate
          python scripts/ingest_tweets.py

      - name: Check if raw_tweets.json exists
        id: check_file
        run: |
          if [ -f "raw_tweets.json" ]; then
            echo "file_exists=true" >> $GITHUB_ENV
          else
            echo "file_exists=false" >> $GITHUB_ENV
          fi

      # Send raw_tweets.json to Foundry
      - name: Send Tweets to Foundry
        if: env.file_exists == 'true'
        env:
          TWEET_FOUNDRY_TOKEN: ${{ secrets.TWEET_FOUNDRY_TOKEN }}
        run: |
          source venv/bin/activate
          python scripts/send_tweets.py

      - name: Skip step
        if: env.file_exists == 'false'
        run: echo "No tweets fetched. Skipping processing step."

      # Run the Reddit ingestion script
      - name: Fetch Reddit Comments with ingest_reddit.py
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
        run: |
          source venv/bin/activate
          python scripts/ingest_reddit.py

      # Send reddit_comments.json to Foundry
      - name: Send Reddit Comments to Foundry
        env:
          REDDIT_FOUNDRY_TOKEN: ${{ secrets.REDDIT_FOUNDRY_TOKEN }}
        run: |
          source venv/bin/activate
          python scripts/send_reddit.py
